python ppo/ppo.py with EX_NAME="ppo_bc_train_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="bc_train" SEEDS="[9456]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 SELF_PLAY_HORIZON="[2e6, 6e6]" TIMESTAMP_DIR=False
python ppo/ppo.py with EX_NAME="ppo_sampling_sp_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="sampling_sp" SEEDS="[9456]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 TIMESTAMP_DIR=False

python ppo/ppo.py with EX_NAME="ppo_bc_train_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="bc_train" SEEDS="[1887]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 SELF_PLAY_HORIZON="[2e6, 6e6]" TIMESTAMP_DIR=False
python ppo/ppo.py with EX_NAME="ppo_sampling_sp_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="sampling_sp" SEEDS="[1887]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 TIMESTAMP_DIR=False

python ppo/ppo.py with EX_NAME="ppo_bc_train_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="bc_train" SEEDS="[5578]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 SELF_PLAY_HORIZON="[2e6, 6e6]" TIMESTAMP_DIR=False
python ppo/ppo.py with EX_NAME="ppo_sampling_sp_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="sampling_sp" SEEDS="[5578]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 TIMESTAMP_DIR=False

python ppo/ppo.py with EX_NAME="ppo_bc_train_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="bc_train" SEEDS="[5987]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 SELF_PLAY_HORIZON="[2e6, 6e6]" TIMESTAMP_DIR=False
python ppo/ppo.py with EX_NAME="ppo_sampling_sp_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="sampling_sp" SEEDS="[5987]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 TIMESTAMP_DIR=False

python ppo/ppo.py with EX_NAME="ppo_bc_train_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="bc_train" SEEDS="[516]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 SELF_PLAY_HORIZON="[2e6, 6e6]" TIMESTAMP_DIR=False
python ppo/ppo.py with EX_NAME="ppo_sampling_sp_random1" layout_name="random1" REW_SHAPING_HORIZON=5e6 PPO_RUN_TOT_TIMESTEPS=1.6e7 LR=1e-3 OTHER_AGENT_TYPE="sampling_sp" SEEDS="[516]" VF_COEF=0.5 MINIBATCHES=15 LR_ANNEALING=1.5 TIMESTAMP_DIR=False
